### PR TITLE
Add debug packages when running tests on Arch Linux

### PR DESCRIPTION
**Pull request by dvzrv**
Add debug packages for the valgrind tests on Arch Linux.
Fix valgrind test.

### CODE REVIEW

**Comment by sadko4u** [comment]
Failed. Another one idea: maybe calling valgrind should be better used with the debug build of LSP plugin?

**Comment by falkTX** [comment]
> calling valgrind should be better used with the debug build of LSP plugin?
> @falkTX?

for investigating leaks and errors sure, but tests should be done against the build that gets delivered to users too.
current error is not related to this anyway

**Comment by sadko4u** [comment]
> for investigating leaks and errors sure, but tests should be done against the build that gets delivered to users too. current error is not related to this anyway

Then we can implement yet another target to test the plugins with debug information enabled.

**Comment by falkTX** [comment]
I was going to comment to try to enable `--leak-check=full`, as it might be an issue not present on archlinux but only on kxstudio packages in my system.

@sadko4u please wait for confirmation before merging PRs, you are acting too quickly here, leaves no time to do extra checks

**Comment by sadko4u** [comment]
Seems that `valgrind` doesn't see symbols for dynamically loaded shared objects:

https://github.com/lsp-plugins/lsp-plugins-art-delay/runs/7028638159?check_suite_focus=true#step:10:23

**Comment by falkTX** [comment]
that is expected, debug/symbol packages for those would have to be installed too.

**Comment by sadko4u** [comment]
> that is expected, debug/symbol packages for those would have to be installed too.

I think we need debug symbols for them since we don't know who has allocated the leaked memory at this moment.

**Comment by falkTX** [comment]
Yes, but it is not carla (checked a few times, and other plugins run fine) and it is not lsp plugins either.
If the leak came from one of these, valgrind would know and report it. but it comes from somewhere else..
Even if we find the leak, we cant fix it / allow leak=full until whatever project has the bug releases a fix and it gets to archlinux as update

**Comment by sadko4u** [comment]
Are you sure that it doesn't come from LSP?

**Comment by falkTX** [comment]
Yes, otherwise it would be quite obvious in the debug build test.
valgrind with `--track-origins=yes` knows where a leak originated from. the lack of symbols from the leak means it comes from an object without debug information

**Comment by sadko4u** [comment]
@falkTX  finally there were memory leaks in LSP Plugins. I got rid of them:
https://github.com/lsp-plugins/lsp-plugins-art-delay/runs/7030363065?check_suite_focus=true
But I still don't understand why valgrind didn't properly got the debug information from the shared object files of LSP Plugins.

**Comment by sadko4u** [comment]
And finally, I found the answer. There is `--keep-debuginfo=yes` missing as an option. After that, all stack traces related to leaks became visible.

**Comment by falkTX** [comment]
btw, you should enable the leak checking on release/normal builds too.
I only had it disabled because I thought it was from a system lib.

there are small cases where debug vs release will run different code, so it is good practice to check on both.
mostly it just doesnt hurt to have anyway.

**Pull request merged**
